POST http://localhost:3333/videos
Content-type: application/json

{
  "title": "node 1",
  "description": "Este é o video 3",
  "duration": 180
}


###

GET http://localhost:3333/videos


###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/cc65b5b8-bed2-48dc-a7de-339e7077588e
Content-type: application/json

{
  "title": "Video 3",
  "description": "Este é o video 1",
  "duration": 180
}


###

DELETE http://localhost:3333/videos/cc65b5b8-bed2-48dc-a7de-339e7077588e